Important Facts to Know :

    NumPy arrays are homogeneous, meaning all elements must be the same type, allowing efficient computation.
    Vectorized operations in NumPy can be 10 to 100 times faster than equivalent Python loops.

Reference:

https://www.geeksforgeeks.org/python/numpy-tutorial/

https://www.geeksforgeeks.org/numpy/python-numpy/





In [28]:
import numpy as np

# creating a 1D array
x = np.array([1, 2, 3])

# 2D array
y = np.array([[1, 2], [3, 4]])

# 3d array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

#creating an numpy array from a tuple
arr = np.array((1, 2, 3, 3, 4, 5))
print (arr)
print ()
print (x)
print (y)
print (z)

[1 2 3 3 4 5]

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
import numpy as np

arr1 = np.zeros((2, 3))
arr2 = np.ones((3, 3))
arr3 = np.ones((2, 2))
arr4 = np.arange(0, 10, 2)

print (arr1)
print ()
print (arr2)
print ()
print (arr3)
print ()
print (arr4)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]]

[0 2 4 6 8]


### Accessing numpy array elements

In [12]:
# Numpy array indexing

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print ("3nd Element: ", arr1[2])
print("3rd element from end: ", arr1[-3])

arr2 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
print ("The array is:\n", arr2)
print ("Element in 1st row, 3rd column :", arr2[0, 2])

3nd Element:  30
3rd element from end:  30
The array is:
 [[1 2 3]
 [4 5 6]
 [5 6 7]]
Element in 1st row, 3rd column : 3


## Slicing : Just like in python lists numpy arrays can also be sliced
As numpy arrays can be multi-dimensional, you need to specify a slice for each dimension of the array

Reference:
https://www.geeksforgeeks.org/python/numpy-slicing-and-indexing/

In [13]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
# elements from index 1 to 3
print ("Range of elements:\n", arr[1:4])

# all rows, second column
print ("Multi-dimensional Slicing:\n", arr[:, 1])


Range of elements:
 [[4 5 6]
 [5 6 7]]
Multi-dimensional Slicing:
 [2 5 6]


In [32]:
arr = np.array([[-1, 2, 3, 4], [4, -0.5, 6, 0], [2.5, 6, 0, 7], [3, -7, 4, 2.0]])

print(arr)
# get the first two rows and alternate columns
arr2 = arr[:2, ::2]
print ()
print (arr2)

#print elements at specific indices
arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

[[-1.   2.   3.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.5  6.   0.   7. ]
 [ 3.  -7.   4.   2. ]]

[[-1.  3.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [20]:
# Advanced Indexing

import numpy as np
arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print (arr)
print (type(arr))
print (arr.shape)

# integer array indexing
indices = np.array([1, 3, 5])
print ("Integer array indexing: ", arr[indices])

cond = arr > 30
print ("\n Elements greater than 0:\n", arr[cond])

[  0  10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>
(11,)
Integer array indexing:  [10 30 50]

 Elements greater than 0:
 [ 40  50  60  70  80  90 100]


In [21]:
# Numpy basic Operations
x = np.array ([1, 2, 3])
y = np.array ([4, 5, 6])

#Addition
add = x + y
print ("Sum:", add)

# Subtraction
sub =  x - y
print ("Sub:", sub)

# Multiplication
prod = x * y
print ("Product:", prod)

# Division
div = x / y
print ("Division:", div)

Sum: [5 7 9]
Sub: [-3 -3 -3]
Product: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [22]:
# Unary operation

arr= np.array([-3, -1, 0, 1, 3])
result = np.absolute(arr)
print ("Absolute value of array:", result)


Absolute value of array: [3 1 0 1 3]


In [23]:
# Numpy Binary operations
import numpy as np

# Two example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Applying a binary operation: addition
result = np.add(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition Result:", result)


Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]


In [24]:
# Numpy ufuncs

import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [26]:
# Numpy Sorting arrays

import numpy as np

# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
print ()
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]

Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [36]:
#Some more basic array operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print ("Adding 2 to each element of the array:\n", a + 2)
print ("Adding -5 to each element of the array:\n", a + (-5))
print ("Subtracting 2 from each element of the array:\n", b - 2)
# unary operations
print ("Sum of all array elements:", a.sum())
# binary operations
print ("Sum of the two arrays:\n",a + b)


Adding 2 to each element of the array:
 [[3 4]
 [5 6]]
Adding -5 to each element of the array:
 [[-4 -3]
 [-2 -1]]
Subtracting 2 from each element of the array:
 [[3 4]
 [5 6]]
Sum of all array elements: 10
Sum of the two arrays:
 [[ 6  8]
 [10 12]]


Methods in Numpy

Reference:
    https://www.geeksforgeeks.org/numpy/python-numpy/


all()
any()
put()
amax()
amin()
argmin()argmax()
insert()
delete()
append()
empty()
reshape()
tile()
compress()
arange()
diag()
absolute()
ceil()
floor()
power()
log()
