In [3]:
import numpy as np

arr = np.random.randint(low = 0, high = 100, size = 15)

print (arr)

[16 31 66 82 40 80  5 35 10 79 44  5  0 56 85]


In [5]:
import numpy as np

arr = np.random.randint(low = 4, high = 9, size=(3, 4))
print (arr)

[[7 7 5 6]
 [6 5 8 7]
 [5 5 4 5]]


In [6]:
import numpy as np
arr = np.random.randint(2, 10, (2, 3, 4))
print (arr)

[[[7 3 8 4]
  [9 4 2 2]
  [2 9 7 8]]

 [[4 9 6 5]
  [8 2 9 3]
  [9 2 8 4]]]
